// src/components/layout/fab.tsx
import { ThemeToggle } from './theme-toggle'

export function Fab() {
  return (
    <div
      flex="~ col items-center justify-between gap-y-2"
      border="~ border rounded-lg"
      bg="white/50 dark:zinc-900/50"
      className="bottom-5 sm:bottom-3rem right-3 sm:right-3rem shadow-black/10 shadow-md transition-all"
      fixed
      z-99
      p-1
      backdrop-blur
    >
      <ThemeToggle />
    </div>
  )
}

// app/components/layout/fab.vue
<script setup lang="ts">
</script>

<template>
  <div
    bottom="5 sm:3rem" right="3 sm:3rem"
    flex="~ col items-center justify-between gap-y-2"
    border="~ border rounded-lg"
    bg="white/50 dark:zinc-900/50"
    class="shadow-black/10 shadow-md transition-all" fixed z-99 p-1
    backdrop-blur
  >
    <LayoutThemeButton />
    <LayoutToTopButton />
  </div>
</template>
