// src/components/article/index.vue
<script setup lang="ts">
import type { JSONParsed } from 'hono/utils/types'
import type { SelectPost } from '~~/server/database/schema'
import { formatDate } from '@vueuse/core'
import { motion } from 'motion-v'

interface Props {
  article: JSONParsed<SelectPost>
  delay?: number
}
const { article, delay = 0 } = defineProps<Props>()
</script>

<template>
  <motion.article
    :initial="{ y: 50, opacity: 0.001 }"
    :animate="{ y: 0, opacity: 1 }"
    :transition="{
      type: 'spring',
      duration: 0.4,
      bounce: 0,
      delay,
    }"
    grid="md:~ md:cols-4 md:items-baseline"
    class="ease-$spring-easing animate-in zoom-in-70 [animation-fill-mode:both]! [animation-range:entry_0%,exit_100%]! [animation-timeline:view(y)]!"
  >
    <div
      relative
      flex="~ col items-start"
      class="group md:col-span-3"
    >
      <ArticleCardTitle :title="article.title" :slug="article.slug" />
      <ArticleCardTime :date="article.publishedAt" class="md:hidden" />

      <div
        relative z-10 text-sm text="zinc-600 dark:zinc-400"
        class="max-w-80ch prose dark:prose-invert"
      >
        <p>{{ article.content }}</p>
      </div>
      <div
        aria-hidden="true"
        relative z-10 mt-4 flex items-center text-sm text-accent font-medium
      >
        立即阅读
        <i inline-block class="i-mingcute:right-small-line ml-1 size-4" />
      </div>
    </div>
    <div relative z-10 order-first class="hidden md:flex" flex="col items-start">
      <time
        mb-3 mt-1 text-sm
        class="text-zinc-500 dark:text-zinc-500"
        :datetime="article.publishedAt"
      >
        {{ formatDate(new Date(article.publishedAt), 'MMM DD YYYY', { locales: 'zh-Hans' }) }}
      </time>
      <div flex="~ gap-1 wrap" pr-10>
        <ArticleTag v-for="tag in []" :key="tag" :tag text-xs />
      </div>
    </div>
  </motion.article>
</template>

// src/components/article/article.tsx
'use client'

import type { Post } from '@/lib/post'
import { format } from 'date-fns'
import { zhCN } from 'date-fns/locale'

import { motion } from 'motion/react'
import { ArticleTag, ArticleTime, ArticleTitle } from '@/components/article/article-items'

interface Props {
  article: Post
}

export function Article({ article }: Props) {
  return (
    <motion.article
      initial={{ opacity: 0, scale: 0.7 }}
      animate={{ opacity: 1, scale: 1 }}
      className="grid md:grid-cols-4 md:items-baseline"
    >
      <div className="group relative flex flex-col items-start md:col-span-3">
        <ArticleTitle article={article} />
        <ArticleTime article={article} className="md:hidden" />
        <p className="relative z-10 mt-2 text-sm text-zinc-600 dark:text-zinc-400">
          {article.excerpt || '这篇文章没有什么好总结的，或者是作者没把总结写好 _(:з」∠)_'}
        </p>
        <div
          aria-hidden="true"
          className="relative z-10 mt-4 flex items-center text-sm font-medium text-accent"
        >
          立即阅读
          <i className="i-[mingcute--right-small-line] ml-1 inline-block size-4" />
        </div>
      </div>
      <div className="relative z-10 order-first hidden flex-col items-start md:flex">
        <time
          className="mb-3 mt-1 text-sm text-zinc-500 dark:text-zinc-500"
          dateTime={article.publishedAt?.toISOString()}
        >
          {format(article.publishedAt, 'MMM dd yyyy', { locale: zhCN })}
        </time>
        <div className="flex flex-wrap gap-1 pr-10">
          {article.tags?.map(tag => (
            <ArticleTag key={tag} tag={tag} className="text-xs" />
          ))}
        </div>
      </div>
    </motion.article>
  )
}
