// src/components/auth/signin-form.vue
<script setup lang="ts">
import type { LoginFormData } from '~/schemas/auth'
import { useMutation } from '@pinia/colada'
import { useForm } from '@tanstack/vue-form'
import { useAuth } from '~/composables/auth'
import { loginSchema } from '~/schemas/auth'

const emit = defineEmits<{
  success: []
  error: [message: string]
}>()

const { signIn } = useAuth()

const { mutate, isLoading } = useMutation({
  mutation(values: LoginFormData) {
    return signIn.email(
      {
        email: values.email,
        password: values.password,
      },
      { throw: true },
    )
  },
  onSuccess() {
    emit('success')
  },
  onError(error) {
    emit('error', error.message)
  },
})

const form = useForm({
  defaultValues: {
    email: '',
    password: '',
  },
  validators: validatorsFromSchema(loginSchema, 'submit'),
  onSubmit: async ({ value }) => {
    mutate(value)
  },
})
</script>

<template>
  <form
    flex="~ col gap-4"
    @submit="(e) => {
      e.preventDefault()
      e.stopPropagation()
      form.handleSubmit()
    }"
  >
    <form.Field name="email">
      <template #default="{ field }">
        <UiFormField
          :field
          label="邮箱地址"
        >
          <template #default="{ value, onInput, onBlur }">
            <input
              :value="value"
              type="email"
              autocomplete="email"
              placeholder="请输入邮箱地址"
              w="full" p="x4 y2"
              border="~ border focus:blue-500 data-[invalid]:red-500 data-[invalid]:focus:red-500 rounded-lg"
              bg="transparent"
              :data-invalid="field.state.meta.errors.length > 0 ? '' : undefined"
              class="text-xs text-zinc-900 outline-none transition-all placeholder:text-xs dark:text-white focus:ring-2 focus:ring-blue-500/20 placeholder-zinc-500 dark:placeholder-zinc-400"
              @input="onInput"
              @blur="onBlur"
            >
          </template>
        </UiFormField>
      </template>
    </form.Field>

    <form.Field name="password">
      <template #default="{ field }">
        <UiFormField
          :field
          label="密码"
        >
          <template #default="{ value, onInput, onBlur }">
            <input
              :value="value"
              type="password"
              autocomplete="current-password"
              placeholder="请输入密码"
              w="full" p="x4 y2"
              border="~ border focus:blue-500 data-[invalid]:red-500 data-[invalid]:focus:red-500 rounded-lg"
              bg="transparent"
              :data-invalid="field.state.meta.errors.length > 0 ? '' : undefined"
              class="text-xs text-zinc-900 outline-none transition-all placeholder:text-xs dark:text-white focus:ring-2 focus:ring-blue-500/20 placeholder-zinc-500 dark:placeholder-zinc-400"
              @input="onInput"
              @blur="onBlur"
            >
          </template>
        </UiFormField>
      </template>
    </form.Field>

    <UiButton
      type="submit"
      :disabled="isLoading"
    >
      {{ isLoading ? '登录中...' : '登录' }}
    </UiButton>
  </form>
</template>

// app/src/components/auth/signin-form.tsx
'use client'

import { Field } from '@ark-ui/react/field'
import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { Button } from '@/components/ui/button'
import { authClient } from '@/lib/auth/client'

const signinSchema = z.object({
  email: z.email('请输入有效的邮箱地址'),
  password: z
    .string()
    .min(1, '请输入密码')
    .min(6, '密码至少需要6个字符'),
})

export function SignInForm() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(signinSchema),
  })

  const { mutate, isPending } = useMutation({
    mutationFn: (data: z.infer<typeof signinSchema>) => {
      return authClient.signIn.email(data)
    },
  })

  const onSubmit = handleSubmit((data) => {
    mutate(data)
  })

  return (
    <form flex="~ col gap-4" onSubmit={onSubmit}>
      <Field.Root space-y-2 invalid={!!errors.email}>
        <Field.Label>邮箱</Field.Label>
        <Field.Input
          type="email"
          autoComplete="email"
          placeholder="请输入邮箱地址"
          w-full
          p="x4 y2"
          border="~ border focus:accent data-[invalid]:red-500 data-[invalid]:focus:red-500 rounded-lg"
          bg="transparent"
          data-invalid={errors.email ? '' : undefined}
          className="text-xs text-zinc-900 outline-none transition-all placeholder:text-xs dark:text-white focus:ring-2 focus:ring-accent placeholder-zinc-500 dark:placeholder-zinc-400"
          {...register('email')}
        />
        {errors.email && (
          <Field.ErrorText inline-block text="xs red-500">
            {errors.email.message}
          </Field.ErrorText>
        )}
      </Field.Root>
      <Field.Root space-y-2 invalid={!!errors.password}>
        <Field.Label>密码</Field.Label>
        <Field.Input
          type="password"
          autoComplete="current-password"
          placeholder="请输入密码"
          w-full
          p="x4 y2"
          border="~ border focus:accent data-[invalid]:red-500 data-[invalid]:focus:red-500 rounded-lg"
          bg="transparent"
          data-invalid={errors.password ? '' : undefined}
          className="text-xs text-zinc-900 outline-none transition-all placeholder:text-xs dark:text-white focus:ring-2 focus:ring-accent placeholder-zinc-500 dark:placeholder-zinc-400"
          {...register('password')}
        />
        {errors.password && (
          <Field.ErrorText inline-block text="xs red-500">
            {errors.password.message}
          </Field.ErrorText>
        )}
      </Field.Root>
      <Button type="submit" disabled={isPending}>
        {isPending ? '登录中...' : '登录'}
      </Button>
    </form>
  )
}
