// src/components/layout/auth-button.vue
<script setup lang="tsx">
import { Avatar } from '@ark-ui/vue/avatar'
import { Menu } from '@ark-ui/vue/menu'
import { useAuth } from '~/composables/auth'

const { loggedIn, user, signOut } = useAuth()

const authModalRef = useTemplateRef('authModalRef')
const manageModalRef = useTemplateRef('manageModalRef')

function openAuthModal() {
  authModalRef.value?.open()
}

function openAccountModal() {
  manageModalRef.value?.open()
}

async function handleSignOut() {
  await signOut()
}
</script>

<template>
  <!-- Auth Modal -->
  <AuthModal ref="authModalRef" />

  <!-- Account Management Modal -->
  <AuthManageModal ref="manageModalRef" />

  <!-- 未登录状态：显示登录按钮 -->
  <button
    v-if="!loggedIn"
    type="button"
    flex="~ items-center justify-center" of-hidden
    class="size-8 bg-opacity-80 transition-all active:scale-105 hover:scale-115"
    title="登录"
    @click="openAuthModal"
  >
    <div class="i-mingcute:user-4-line size-4" />
  </button>

  <!-- 已登录状态：显示用户头像菜单  -->
  <Menu.Root
    v-else
    :positioning="{
      placement: 'left',
    }"
  >
    <Menu.Trigger
      type="button"
      flex="~ items-center justify-center"
      size-8 of-hidden p-1
      class="transition-all active:scale-105 hover:scale-115"
    >
      <Avatar.Root of-hidden rounded-full>
        <Avatar.Fallback
          size-full
          flex="data-[state=visible]:inline items-center justify-center"
        >
          {{ user?.name?.charAt(0).toUpperCase() ?? 'U' }}
        </Avatar.Fallback>
        <Avatar.Image :src="user?.image ?? ''" alt="avatar" />
      </Avatar.Root>
    </Menu.Trigger>
    <Menu.Positioner>
      <Menu.Content
        min-w-32 p-2
        border="~ border rounded-lg"
        bg="white/50 dark:zinc-900/50"
        class="shadow-black/10 shadow-md backdrop-blur-10px transition-all"
        backdrop-blur-2xl
      >
        <div px-1 space-y-1>
          <h4 text-xs op-70>
            账户
          </h4>
          <div flex="~ items-center justify-center gap-1" of-hidden>
            <Avatar.Root size-6 of-hidden rounded-full>
              <Avatar.Fallback
                size-full
                flex="data-[state=visible]:inline items-center justify-center"
              >
                {{ user?.name?.charAt(0).toUpperCase() ?? 'U' }}
              </Avatar.Fallback>
              <Avatar.Image :src="user?.image ?? ''" alt="avatar" />
            </Avatar.Root>

            <span flex-1 text-xs>
              {{ user?.name }}
            </span>
          </div>
        </div>
        <Menu.Separator my-1 border="~ border" />
        <Menu.Item
          v-if="user?.role === 'admin'"
          value="account"
          as-child
        >
          <RouterLink
            p="x2 y1.5"
            flex="~ items-center gap-2"
            bg="transparent hover:zinc-200/50 dark:hover:zinc-700/50"
            cursor-pointer rounded text-xs
            to="/dashboard"
          >
            <div class="i-mingcute:dashboard-2-line size-4" />
            <span>后台管理</span>
          </RouterLink>
        </Menu.Item>
        <Menu.Item
          value="account"
          p="x2 y1.5"
          flex="~ items-center gap-2"
          bg="transparent hover:zinc-200/50 dark:hover:zinc-700/50"
          cursor-pointer
          rounded text-xs @click="openAccountModal"
        >
          <div class="i-mingcute:settings-3-line size-4" />
          <span>账户管理</span>
        </Menu.Item>
        <Menu.Item
          value="signout"
          p="x2 y1.5"
          flex="~ items-center gap-2"
          bg="transparent hover:zinc-200/50 dark:hover:zinc-700/50"
          cursor-pointer
          rounded text-xs @click="handleSignOut"
        >
          <div class="i-mingcute:exit-line size-4" />
          <span>退出登录</span>
        </Menu.Item>
      </Menu.Content>
    </Menu.Positioner>
  </Menu.Root>
</template>

// src/components/layout/auth-button.tsx
'use client'

import { Menu, Portal } from '@ark-ui/react'
import { useAuthContext } from '@/hooks/auth/context'
import { authClient } from '@/lib/auth/client'
import { AuthModal } from '../auth/modal'
import { UserAvatar } from '../auth/user-avatar'

export function AuthButton() {
  const { user } = useAuthContext()

  if (!user) {
    return (
      <AuthModal>
        <button
          type="button"
          flex="~ items-center justify-center"
          of-hidden
          className="size-8 bg-opacity-80 transition-all active:scale-105 hover:scale-115"
          title="登录"
        >
          <span className="sr-only">登录</span>
          <div className="i-mingcute:user-4-line size-4" />
        </button>
      </AuthModal>
    )
  }

  return (
    <Menu.Root positioning={{ placement: 'left' }}>
      <Menu.Trigger
        type="button"
        flex="~ items-center justify-center"
        size-8
        of-hidden
        p-1
        className="transition-all active:scale-105 hover:scale-115"
      >
        <UserAvatar user={user} />
      </Menu.Trigger>
      <Portal>
        <Menu.Positioner>
          <Menu.Content
            min-w-32
            p-2
            border="~ border rounded-lg"
            bg="white/50 dark:zinc-900/50"
            className="shadow-black/10 shadow-md transition-all"
            backdrop-blur
          >
            <div px-1 space-y-1>
              <h4 text-xs op-70>
                账户
              </h4>
              <div flex="~ items-center justify-center gap-1" of-hidden>
                <UserAvatar size-6 user={user} />
                <span flex-1 text-xs>
                  {user?.name}
                </span>
              </div>
            </div>
            <Menu.Separator my-1 border="~ border" />
            {user?.role === 'admin' && (
              <Menu.Item
                value="admin"
                asChild
              >
                <a
                  p="x2 y1.5"
                  flex="~ items-center gap-2"
                  bg="transparent hover:zinc-200/50 dark:hover:zinc-700/50"
                  cursor-pointer
                  rounded
                  text-xs
                  href="/admin"
                >
                  <div className="i-mingcute:dashboard-2-line size-4" />
                  <span>后台管理</span>
                </a>
              </Menu.Item>
            )}
            <Menu.Item
              value="account"
              p="x2 y1.5"
              flex="~ items-center gap-2"
              bg="transparent hover:zinc-200/50 dark:hover:zinc-700/50"
              cursor-pointer
              rounded
              text-xs
            >
              <div className="i-mingcute:settings-3-line size-4" />
              <span>账户管理</span>
            </Menu.Item>
            <Menu.Item
              value="signout"
              p="x2 y1.5"
              flex="~ items-center gap-2"
              bg="transparent hover:zinc-200/50 dark:hover:zinc-700/50"
              cursor-pointer
              rounded
              text-xs
              onClick={() => {
                authClient.signOut()
              }}
            >
              <div className="i-mingcute:exit-line size-4" />
              <span>退出登录</span>
            </Menu.Item>
          </Menu.Content>
        </Menu.Positioner>
      </Portal>
    </Menu.Root>
  )
}
