// app/src/components/layout/to-top-button.tsx
'use client'

import { AnimatePresence, motion, useMotionValueEvent, useScroll } from 'motion/react'
import { useState } from 'react'

export function ToTopButton() {
  const { scrollY } = useScroll()
  const [isVisible, setIsVisible] = useState(false)

  useMotionValueEvent(scrollY, 'change', (latest) => {
    setIsVisible(latest > 100)
  })

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.button
          initial={{ opacity: 0, height: `0` }}
          animate={{ opacity: 1, height: `2rem` }}
          exit={{ opacity: 0, height: `0` }}
          transition={{
            type: 'spring',
            duration: 0.2,
          }}
          type="button"
          flex="~ items-center justify-center"
          of-hidden
          className="size-8 bg-opacity-80 transition-all active:scale-105 hover:scale-115"
          onClick={() => {
            window.scrollTo({
              top: 0,
              behavior: 'smooth',
            })
          }}
        >
          <span className="sr-only">back to top</span>
          <i inline-block className="i-mingcute:up-line" />
        </motion.button>
      )}
    </AnimatePresence>
  )
}

// app/components/layout/home/to-top-button.vue
<script setup lang="ts">
const { y } = useWindowScroll()
</script>

<template>
  <Transition
    enter-active-class="transition-property-[height,opacity] duration-300 ease-in-out"
    leave-active-class="transition-property-[height,opacity] duration-300 ease-in-out"
    enter-from-class="h-0 op-0"
    leave-to-class="h-0 op-0"
  >
    <button
      v-if="y > 100"
      type="button"
      flex="~ items-center justify-center" of-hidden
      class="[&:is(:hover,:active)_[class^=i-]]:scale-115 [&_[class^=i]]:transition-all size-8 bg-op-80"
      @click="y = 0"
    >
      <span class="sr-only">back to top</span>
      <div class="i-mingcute:up-line" />
    </button>
  </Transition>
</template>
